--ANTHONY RODRIGUEZ VALVERDE.9
--TERCERA PARTE PROYECTO FINAL BASES DE DATOS
--FECHA DE INICIO 15/02/2023
--FECHA FINALIZACION 17/02/2023
CREATE DATABASE MATRICULA_PROYECTO 
GO
USE MATRICULA_PROYECTO
GO
--***********************************************************************************************
--CREAMOS LAS TABLAS DE LA BASE DE DATOS

/*TABLA ESTUDIANTES*/
CREATE TABLE ESTUDIANTES(
	CARNET_ESTUDIANTE VARCHAR(15) PRIMARY KEY,
	ID_ESTUDIANTE VARCHAR(20) NOT NULL UNIQUE,
	NOMBRE VARCHAR(15) NOT NULL,
	APELLIDO1_EST VARCHAR(15) NOT NULL,
	APELLIDO2_EST VARCHAR(15),
	CORREO_EST VARCHAR(30),
	TELEFONO_ESTUDIANTE VARCHAR(8),
	FECHA_INGRESO DATE NOT NULL DEFAULT GETDATE(),
	ESTADO_ESTUDIANTE VARCHAR(3) NOT NULL DEFAULT 'ACT',
	BORRADO_E BIT NOT NULL DEFAULT 0
);

/*TABLA PROFESORES*/
CREATE TABLE PROFESORES(
	ID_PROFESOR VARCHAR(20) PRIMARY KEY,
	NOMBRE_PROFESOR VARCHAR(15) NOT NULL,
	APELLIDO1_PRO VARCHAR(15) NOT NULL,
	APELLIDO2_PRO VARCHAR(15),
	CORREO_PRO VARCHAR(30)NOT NULL,
	TELEFONO_PRO VARCHAR(8),
	DIRECCION_PRO VARCHAR(150),
	ESTADO_PRO VARCHAR(3) NOT NULL DEFAULT 'ACT',
	BORRADO_P BIT NOT NULL DEFAULT 0
);

/*TABLA LABORATORIOS*/
CREATE TABLE LABORATORIOS(
	ID_LAB VARCHAR(15) PRIMARY KEY,
	DISPONIBILIDAD VARCHAR(20) NOT NULL,
	DIRECCION_LAB VARCHAR(150)
);
 
/*TABLA CARRERAS*/
CREATE TABLE CARRERAS(
	COD_CARRERA VARCHAR(20) PRIMARY KEY,
	NOMBRE_CARRERA VARCHAR(20) NOT NULL,
	GRADO VARCHAR(15) NOT NULL,
	CUPOS INT NOT NULL
);

/*TABLA MODULOS*/
CREATE TABLE MODULOS(
	COD_MODULO VARCHAR(15) PRIMARY KEY,
	COD_CARRERA VARCHAR(20),
	CUPOS INT,
	NOMBRE_MODULO VARCHAR(20) NOT NULL,
	MONTO DECIMAL(10,2)NOT NULL,
	DURACION INT NOT NULL
);

/*TABLA DIAS_FERIADOS*/
CREATE TABLE DIAS_FERIADOS(
	COD_DIAS_FERIADOS VARCHAR(15) PRIMARY KEY,
	FECHA_FERIADOS DATE NOT NULL
);

/*TABLA CALIFICACIONES*/
CREATE TABLE CALIFICACIONES_EST(
	NOTAS_EST INT PRIMARY KEY,
	CARNET_ESTUDIANTE  VARCHAR(15),
	COD_MODULO VARCHAR(15)
);

/*TABLA CERTIFICAIONES*/
CREATE TABLE CERTIFICACIONES(
	COD_CERTIFICACIONES VARCHAR(30) PRIMARY KEY,
	NOMBRE_CERTIFICACIONES VARCHAR(20) NOT NULL,
	BORRADO_CERTIFICACIONES BIT NOT NULL DEFAULT 0
); 
	
/*TABLA MATRICULA*/
CREATE TABLE MATRICULA(
	NUM_RECIBO INT PRIMARY KEY,
	CARNET_ESTUDIANTE VARCHAR(15),
	FECHA_MATRICULA DATE NOT NULL DEFAULT GETDATE(),
	ESTADO_MATRICULA VARCHAR(5)NOT NULL,
	USUARIO_MATRICULA VARCHAR(25),
	OBSERVACIONES_MATRICULA VARCHAR(150)
);

/*TABLA DETALLES_MATRICULA*/
CREATE TABLE PAGOS(
	CARNET_ESTUDIANTE VARCHAR(15),
	COD_MODULO VARCHAR(15),
	FECHA_PAGO DATE NOT NULL DEFAULT GETDATE()
);

/*TABLA MODULOS_ABIERTOS*/
CREATE TABLE MODULOS_ABIERTOS(
	MODULO_ABI VARCHAR(30) PRIMARY KEY,
	COD_MODULO VARCHAR(15),
	ID_PROFESOR VARCHAR(20),
	ID_LAB VARCHAR(15),
	REQUISITOS VARCHAR(150)
);

/*TABLA GRUPOS*/
CREATE TABLE GRUPOS(
	ID_GRUPO VARCHAR(15) PRIMARY KEY,
	MODULO_ABI VARCHAR(30),
	NOMBRE_GRUPO VARCHAR(20),
	CUPOS INT
);

/*TABLA HORARIOS*/
CREATE TABLE HORARIOS(
	ID_GRUPO VARCHAR(15),
	HORA_INICIO TIME,
	HORA_FINAL TIME,
	TOTAL_DIAS INT
);

/*TABLA DETALLE_MATRICULA*/
CREATE TABLE DETALLE_MATRICULA(
	NUM_RECIBO INT,
	MODULO_ABI VARCHAR(30),
	ESTADO_DM   VARCHAR(5)NOT NULL,
	OBSERVACIONES    VARCHAR(200)
);

CREATE TABLE CERTIFICADOS_PROF(
	COD_CERTIFICACIONES VARCHAR(30),
	ID_PROFESOR VARCHAR(20)
);

--***********************************************************************************************
--CREAMOS LAS RELACIONES

ALTER TABLE CERTIFICADOS_PROF
	ADD CONSTRAINT FK_ID_PROFESOR_C FOREIGN KEY(ID_PROFESOR) REFERENCES PROFESORES(ID_PROFESOR)

ALTER TABLE CERTIFICADOS_PROF
	ADD CONSTRAINT FK_COD_CERTIFICACIONES_C FOREIGN KEY(COD_CERTIFICACIONES) REFERENCES CERTIFICACIONES(COD_CERTIFICACIONES)

ALTER TABLE DETALLE_MATRICULA
	ADD CONSTRAINT FK_NUM_RECIBO_DM FOREIGN KEY (NUM_RECIBO) REFERENCES MATRICULA(NUM_RECIBO)

ALTER TABLE DETALLE_MATRICULA
	ADD CONSTRAINT FK_MODULO_ABI_DM FOREIGN KEY (MODULO_ABI) REFERENCES MODULOS_ABIERTOS(MODULO_ABI)

ALTER TABLE HORARIOS
	ADD CONSTRAINT FK_ID_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS(ID_GRUPO)

ALTER TABLE GRUPOS
	ADD CONSTRAINT FK_MODULO_ABI FOREIGN KEY (MODULO_ABI) REFERENCES MODULOS_ABIERTOS(MODULO_ABI)

ALTER TABLE MODULOS_ABIERTOS
	ADD CONSTRAINT FK_COD_MODULO_A FOREIGN KEY (COD_MODULO) REFERENCES MODULOS(COD_MODULO)

ALTER TABLE MODULOS_ABIERTOS
	ADD CONSTRAINT FK_ID_PROFESOR_A FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID_PROFESOR)

ALTER TABLE MODULOS_ABIERTOS
	ADD CONSTRAINT FK_LAB_A FOREIGN KEY (ID_LAB) REFERENCES LABORATORIOS(ID_LAB)

ALTER TABLE PAGOS
	ADD CONSTRAINT FK_CARNET_EP FOREIGN KEY (CARNET_ESTUDIANTE) REFERENCES ESTUDIANTES(CARNET_ESTUDIANTE)

ALTER TABLE PAGOS
	ADD CONSTRAINT FK_COD_MODULOP FOREIGN KEY (COD_MODULO) REFERENCES MODULOS(COD_MODULO)

ALTER TABLE MATRICULA
	ADD CONSTRAINT FK_CARNET_EM FOREIGN KEY (CARNET_ESTUDIANTE) REFERENCES ESTUDIANTES(CARNET_ESTUDIANTE)

ALTER TABLE CALIFICACIONES_EST
	ADD CONSTRAINT FK_CARNET_ESTUDIANTE FOREIGN KEY (CARNET_ESTUDIANTE) REFERENCES ESTUDIANTES(CARNET_ESTUDIANTE)

ALTER TABLE CALIFICACIONES_EST
	ADD CONSTRAINT FK_COD_MODULO FOREIGN KEY (COD_MODULO) REFERENCES MODULOS(COD_MODULO)

ALTER TABLE MODULOS 
	ADD CONSTRAINT FK_COD_CARRERA FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA)

